In [63]:
import pandas as pandas
import numpy as  numpy
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
df=sns.load_dataset('tips')

In [49]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [50]:
from sklearn.preprocessing  import LabelEncoder
encoder=LabelEncoder()   #-> initialize encoder

encoded_data=encoder.fit_transform(df['time'])

In [51]:
encoder_time=LabelEncoder()   #-> initialize encoder

encoded_data=encoder_time.fit_transform(df['time'])

In [52]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [53]:
for category ,number in zip(encoder_time.classes_,range(len(encoder_time.classes_))):
    print(category,'-------',number)

Dinner ------- 0
Lunch ------- 1

In [54]:
#  for enumerate 
for number, category in enumerate(encoder_time.classes_):
    print(category, '-------', number)

Dinner ------- 0
Lunch ------- 1

In [55]:
encoder_day=LabelEncoder()   #-> initialize encoder

encoded_data=encoder_day.fit_transform(df['day'])

In [56]:
encoder_day.classes_

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [57]:
for category, number in zip(encoder_day.classes_,range(len(encoder_day.classes_))):
    print(category, '-------', number)

Fri ------- 0
Sat ------- 1
Sun ------- 2
Thur ------- 3

In [58]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [59]:
from sklearn.preprocessing  import  OneHotEncoder

In [60]:
ohe=OneHotEncoder(sparse_output=False )
ohe.fit_transform(df[['smoker','sex']])

array([[1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [61]:
ohe=OneHotEncoder(sparse_output=False ,drop='first')
ohe_encoder=ohe.fit_transform(df[['smoker','sex']])
ohe_encoder

array([[0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 0.]])

In [ ]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

In [70]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  smoker_Yes  sex_Male
0         16.99  1.01  Female     No   Sun  Dinner     2         0.0       0.0
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61  Female     No   Sun  Dinner     4         0.0       0.0
..          ...   ...     ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1.0       1.0
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00  Female     No  Thur  Dinner     2         0.0       0.0

[244 rows x 9 columns]

In [77]:
from sklearn.preprocessing  import FunctionTransformer
import numpy as np

In [79]:
log=FunctionTransformer(np.log10)
log.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [80]:
log_2=FunctionTransformer(np.log2)
log_2.fit_transform(df['tip'])

0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

In [93]:
from sklearn.preprocessing import  PowerTransformer

In [108]:
# for yeo-jonhson method using  negative value
X=np.array([
    [-1],
    [0],
    [3],
    [5],
    [10],
    [50]
])
pt=PowerTransformer(method='yeo-johnson')
X_transformed=pt.fit_transform(X)
print('original:')
print(X.ravel())
print('\nTransformed:')
print(np.round(X_transformed.ravel(),3))
print('nLearned lambda:')
print(pt.lambdas_)

original:
[-1  0  3  5 10 50]

Transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]
nLearned lambda:
[0.09126797]

In [114]:
# for Box-cox method using  positive value
y=np.array([[1],[1],[3],[5],[10],[50]])
# create the transformed
pt=PowerTransformer(method='box-cox')
# fit and transformed
y_transformed=pt.fit_transform(y)
print('original:')
print(y.ravel())
print('\nTransformed:')
print(np.round(y_transformed.ravel(),3))
print('nLearned lambda:')
print(pt.lambdas_)

original:
[ 1  1  3  5 10 50]

Transformed:
[-1.205 -1.205 -0.15   0.255  0.73   1.574]
nLearned lambda:
[-0.23784507]

In [137]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vikas'],
    'Gender': ['Male', 'Female', np.nan, 'Female', 'Male'],          # Categorical with Null
    'City': ['Delhi', 'Mumbai', 'Delhi', np.nan, 'Bangalore'],       # Categorical with Null
    'Age': [25, np.nan, 30, 22, np.nan],                            # Numerical with Null
    'Salary': [50000, 60000, np.nan, 45000, 70000],
    'department':['HR','NaN','Finance','IT','IT']               # Numerical with Null
}

df = pd.DataFrame(data)
df

    Name  Gender       City   Age   Salary department
0   Amit    Male      Delhi  25.0  50000.0         HR
1  Priya  Female     Mumbai   NaN  60000.0        NaN
2  Rahul     NaN      Delhi  30.0      NaN    Finance
3  Sneha  Female        NaN  22.0  45000.0         IT
4  Vikas    Male  Bangalore   NaN  70000.0         IT

In [139]:
from sklearn.impute import SimpleImputer

In [140]:
imputer=SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']])

array([[50000.],
       [60000.],
       [56250.],
       [45000.],
       [70000.]])

In [141]:
imputer=SimpleImputer(strategy='mean')
df['new_salary']=imputer.fit_transform(df[['Salary']]).flatten()

In [142]:
df

    Name  Gender       City   Age   Salary department  new_salary
0   Amit    Male      Delhi  25.0  50000.0         HR     50000.0
1  Priya  Female     Mumbai   NaN  60000.0        NaN     60000.0
2  Rahul     NaN      Delhi  30.0      NaN    Finance     56250.0
3  Sneha  Female        NaN  22.0  45000.0         IT     45000.0
4  Vikas    Male  Bangalore   NaN  70000.0         IT     70000.0

In [143]:
imputer=SimpleImputer(strategy='median')
df['median_salary']=imputer.fit_transform(df[['Salary']]).flatten()

In [144]:
df

,Name,Gender,City,Age,Salary,department,new_salary,median_salary
0,Amit,Male,Delhi,25.0,50000.0,HR,50000.0,50000.0
1,Priya,Female,Mumbai,NaN,60000.0,NaN,60000.0,60000.0
2,Rahul,NaN,Delhi,30.0,NaN,Finance,56250.0,55000.0
3,Sneha,Female,NaN,22.0,45000.0,IT,45000.0,45000.0
4,Vikas,Male,Bangalore,NaN,70000.0,IT,70000.0,70000.0

In [148]:
imputer=SimpleImputer(strategy='most_frequent',)
df['new_cityt']=imputer.fit_transform(df[['City']]).flatten()

In [149]:
df

,Name,Gender,City,Age,Salary,department,new_salary,median_salary,new_cityt
0,Amit,Male,Delhi,25.0,50000.0,HR,50000.0,50000.0,Delhi
1,Priya,Female,Mumbai,NaN,60000.0,NaN,60000.0,60000.0,Mumbai
2,Rahul,NaN,Delhi,30.0,NaN,Finance,56250.0,55000.0,Delhi
3,Sneha,Female,NaN,22.0,45000.0,IT,45000.0,45000.0,Delhi
4,Vikas,Male,Bangalore,NaN,70000.0,IT,70000.0,70000.0,Bangalore